# Generated by Django 4.1 on 2022-08-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleBlog', models.CharField(max_length=100, verbose_name='Название блога')),
                ('subtitleBlog', models.CharField(max_length=100, verbose_name='Категория? блога')),
                ('descriptionBlog', models.TextField(verbose_name='Описание блога')),
                ('createdBlog', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('changedBlog', models.DateField(auto_now=True, verbose_name='Дата последнего измения')),
                ('activeBlog', models.BooleanField(default=True, verbose_name='Публикуем?')),
                ('pictureBlog', models.FileField(blank=True, upload_to='JohnWebSite/img', verbose_name='Картинка блога')),
                ('linkBlog', models.URLField(blank=True, max_length=255, verbose_name='Адрес блога в интернете')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-createdBlog'],
            },
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helloExtUser', models.CharField(max_length=255, verbose_name='Приветствие на первом экране')),
                ('descriptionExtUser', models.TextField(max_length=1000, verbose_name='Описание на первом экране')),
                ('pictureExtUser', models.FileField(blank=True, null=True, upload_to='JohnWebSite/img', verbose_name='Картинка на первом экране')),
                ('resumeExtUser', models.FileField(blank=True, null=True, upload_to='JohnWebSite/resume', verbose_name='Файл резюме')),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзер',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleProject', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('subtitleProject', models.CharField(max_length=100, verbose_name='Категория? проекта')),
                ('descriptionProject', models.TextField(verbose_name='Описание проекта')),
                ('createdProject', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('activeProject', models.BooleanField(default=True, verbose_name='Публикуем?')),
                ('pictureProject', models.FileField(blank=True, upload_to='JohnWebSite/img', verbose_name='Картинка проекта')),
                ('linkProject', models.URLField(max_length=255, unique=True, verbose_name='Адрес проекта в интернете')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-createdProject'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSocial', models.CharField(max_length=100, verbose_name='Название социальной сети')),
                ('pictureSocial', models.FileField(upload_to='JohnWebSite/img', verbose_name='Картинка социальной сети')),
                ('linkSocial', models.URLField(max_length=255, unique=True, verbose_name='Ссылка на социальную сеть')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
