# Generated by Django 4.1 on 2022-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnWebSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-createdBlog'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='extuser',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-createdProject'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterField(
            model_name='project',
            name='linkProject',
            field=models.URLField(max_length=255, unique=True, verbose_name='Адрес проекта в интернете'),
        ),
    ]
