# Generated by Django 4.1 on 2022-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnWebSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activeProject',
            field=models.BooleanField(default=True, verbose_name='Публикуем?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdProject',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pictureProject',
            field=models.FileField(blank=True, upload_to='JohnWebSite/img', verbose_name='Картинка проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitleProject',
            field=models.CharField(max_length=100, verbose_name='Категория? проекта'),
        ),
    ]
