# Generated by Django 4.1 on 2022-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JohnWebSite', '0002_project_activeproject_alter_project_createdproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='linkBlog',
            field=models.URLField(blank=True, max_length=255, verbose_name='Адрес блога в интернете'),
        ),
        migrations.AddField(
            model_name='blog',
            name='pictureBlog',
            field=models.FileField(blank=True, upload_to='JohnWebSite/img', verbose_name='Картинка блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='activeBlog',
            field=models.BooleanField(default=True, verbose_name='Публикуем?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='changedBlog',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего измения'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='createdBlog',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitleBlog',
            field=models.CharField(max_length=100, verbose_name='Категория? блога'),
        ),
    ]
